packages:
  - apps/**
  - assets/**
  - libs/**
  - www/**

catalog:
  '@biomejs/biome': ^1.9.4
  sass-embedded: ^1.85.0
  typescript: ^5.8.2
  vite: ^6.2.0
  vue: ^3.5.13
  vue-tsc: ^2.2.8

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
